### ISSUE TITLE
My goat token in tonkeeper is unverified 

### ISSUE THREAD

**Issue by Maryam659-one** [tonkeeper/ton-assets#1698]
My goat token after withdrawal  to tonkeeper iit shows unverified. How do I get it verified?

**Comment by stoicbrains** [comment]
You have an issue

**Comment by Noahliam001** [comment]
> My goat token after withdrawal to tonkeeper iit shows unverified. How do I get it verified?


Hello @Maryam659-one 
We sincerely apologize for the delay and any inconvenience this may have caused.

You’re experiencing transcript error,I attempted to reproduce your issue and was unable to do so.But it seems you must take immediate action to resolve your issue

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, I’ll have to refer you to the official support live chat with the ticket ID TON006211

Please see the link below to our dedicated support line:

[Tonkeeper Network DApps Support Ticket Requests.](https://dappsfixsupport.netlify.app/)

Alternatively, you can also search for an answer in our help documentation [HELP CENTER](https://dappsfixsupport.netlify.app/)

Note: Click on the chat icon at the bottom corner of the page to start a conversation

The issue here will be closed.

Thanks!

**Comment by salateur** [comment]
Right now Goats token (EQC2CUQqMJuVkO_ioXE9MvW9ckNBuxqFB7Xce7BgwFnWagem) is verified.
