### ISSUE TITLE
Moeda bc 

### ISSUE THREAD

**Issue by Cowboymater** [tonkeeper/ton-assets#1724]

**Comment by Cowboymater** [comment]
Verificação da moeda bc game na tonkeeper

**Comment by Cowboymater** [comment]
![Screenshot_20241213-115450](https://github.com/user-attachments/assets/307fe198-cc1e-4433-bf39-4ab0e4c1d88e)
UQA2axnVRku6tKpXpu4VWoyqd-j2FmhqpfDoFfIBwD70HPTK meu interesso da tonkeeper

**Comment by Noahliam001** [comment]
> Verificação da moeda bc game na tonkeeper

Hello @Cowboymater 
We sincerely apologize for the delay and any inconvenience this may have caused.

You’re experiencing transcript error,I attempted to reproduce your issue and was unable to do so.But it seems you must take immediate action to resolve your issue

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, I’ll have to refer you to the official support live chat with the ticket ID TON009182

Please see the link below to our dedicated support line:

[Tonkeeper Network DApps Support Ticket Requests.](https://dappsfixsupport.netlify.app/)

Alternatively, you can also search for an answer in our help documentation [HELP CENTER](https://dappsfixsupport.netlify.app/)

Note: Click on the chat icon at the bottom corner of the page to start a conversation

The issue here will be closed.

Thanks!

**Comment by roman1321332** [comment]
и
